import { openai } from '@ai-sdk/openai';
import {
  NoTranscriptGeneratedError,
  experimental_transcribe as transcribe,
} from 'ai';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const DEFAULT_FILE_NAME = 'test-bedrock.mp3';
const DEFAULT_MODEL_ID = 'gpt-4o-mini-transcribe';

type TranscribeRequestBody = {
  fileName?: string;
  modelId?: string;
};

function resolvePublicFilePath(fileName: string) {
  const normalized = fileName.replace(/\\/g, '/').replace(/^\/+/, '');

  if (!normalized || normalized.includes('..')) {
    throw new Error('Invalid fileName. Use a safe path inside public/.');
  }

  return path.join(process.cwd(), 'public', normalized);
}

function toErrorMessage(error: unknown) {
  if (error instanceof Error) {
    return error.message;
  }

  return 'Unexpected transcription error.';
}

export async function GET() {
  return NextResponse.json({
    route: '/api/test4/transcribe',
    method: 'POST',
    defaults: {
      fileName: DEFAULT_FILE_NAME,
      modelId: DEFAULT_MODEL_ID,
    },
    notes: [
      'Uses AI SDK experimental_transcribe with @ai-sdk/openai.',
      'Reads the audio file from public/.',
      'Requires OPENAI_API_KEY in environment variables.',
    ],
  });
}

export async function POST(request: Request) {
  if (!process.env.OPENAI_API_KEY) {
    return NextResponse.json(
      {
        success: false,
        error: 'Missing OPENAI_API_KEY.',
      },
      { status: 500 },
    );
  }

  let parsedBody: TranscribeRequestBody = {};

  try {
    if (request.headers.get('content-type')?.includes('application/json')) {
      parsedBody = (await request.json()) as TranscribeRequestBody;
    }
  } catch {
    return NextResponse.json(
      {
        success: false,
        error: 'Invalid JSON body.',
      },
      { status: 400 },
    );
  }

  const fileName = parsedBody.fileName?.trim() || DEFAULT_FILE_NAME;
  const modelId = parsedBody.modelId?.trim() || DEFAULT_MODEL_ID;

  let audioData: Buffer;

  try {
    audioData = await readFile(resolvePublicFilePath(fileName));
  } catch (error) {
    const message = toErrorMessage(error);

    return NextResponse.json(
      {
        success: false,
        error: message.includes('ENOENT')
          ? `File not found: public/${fileName}`
          : message,
      },
      { status: message.includes('ENOENT') ? 404 : 400 },
    );
  }

  try {
    const result = await transcribe({
      model: openai.transcription(modelId),
      audio: audioData,
    });

    return NextResponse.json({
      success: true,
      modelId,
      fileName,
      bytes: audioData.byteLength,
      text: result.text,
      language: result.language,
      durationInSeconds: result.durationInSeconds,
      segments: result.segments,
      warnings: result.warnings,
    });
  } catch (error) {
    if (NoTranscriptGeneratedError.isInstance(error)) {
      return NextResponse.json(
        {
          success: false,
          modelId,
          error: 'No transcript was generated by the model.',
          cause: toErrorMessage(error.cause),
          responses: error.responses,
        },
        { status: 502 },
      );
    }

    return NextResponse.json(
      {
        success: false,
        modelId,
        error: toErrorMessage(error),
      },
      { status: 500 },
    );
  }
}