import { openai } from '@ai-sdk/openai';
import {
  NoTranscriptGeneratedError,
  experimental_transcribe as transcribe,
} from 'ai';
import { NextResponse } from 'next/server';

export const runtime = 'nodejs';

const DEFAULT_MODEL_ID = 'whisper-1';

function toErrorMessage(error: unknown) {
  if (error instanceof Error) {
    return error.message;
  }

  return 'Unexpected transcription error.';
}

export async function POST(request: Request) {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    return NextResponse.json(
      { error: 'OPENAI_API_KEY is not configured.' },
      { status: 500 },
    );
  }

  const incomingFormData = await request.formData();
  const file = incomingFormData.get('file');

  if (!(file instanceof File)) {
    return NextResponse.json(
      { error: 'Missing audio file in request.' },
      { status: 400 },
    );
  }

  const modelValue = incomingFormData.get('model');
  const languageValue = incomingFormData.get('language');
  const promptValue = incomingFormData.get('prompt');

  const modelId =
    typeof modelValue === 'string' && modelValue.trim().length > 0
      ? modelValue
      : DEFAULT_MODEL_ID;

  const language =
    typeof languageValue === 'string' && languageValue.trim().length > 0
      ? languageValue.trim()
      : undefined;

  const prompt =
    typeof promptValue === 'string' && promptValue.trim().length > 0
      ? promptValue.trim()
      : undefined;

  const audio = new Uint8Array(await file.arrayBuffer());

  try {
    const result = await transcribe({
      model: openai.transcription(modelId),
      audio,
      providerOptions:
        language || prompt
          ? {
              openai: {
                ...(language ? { language } : {}),
                ...(prompt ? { prompt } : {}),
              },
            }
          : undefined,
    });

    return NextResponse.json({
      text: result.text,
      language: result.language,
      durationInSeconds: result.durationInSeconds,
      segments: result.segments,
      warnings: result.warnings,
    });
  } catch (error) {
    if (NoTranscriptGeneratedError.isInstance(error)) {
      return NextResponse.json(
        {
          error: 'No transcript was generated by the model.',
          cause: toErrorMessage(error.cause),
          responses: error.responses,
        },
        { status: 502 },
      );
    }

    return NextResponse.json(
      {
        error: toErrorMessage(error),
      },
      { status: 500 },
    );
  }
}
